name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  sanity:
    name: Sanity (${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Lint code
        run: make lint

      - name: Sanity checks
        run: make sanity

  plan:
    name: Plan update
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package-storage-ref: ["production", "staging", "snapshot"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout assets
        run: |
          git worktree add assets/${{ matrix.package-storage-ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Checkout package-storage
        uses: actions/checkout@v2
        with:
          repository: elastic/package-storage
          ref: ${{ matrix.package-storage-ref }}
          path: packages/${{ matrix.package-storage-ref }}

      - name: Calculate diff
        run: python3 -m bot diff

  integrations:
    name: Integrations
    runs-on: ubuntu-latest

    steps:
      - name: Install elastic-package
        run: |
          go install github.com/elastic/elastic-package@latest
          ~/go/bin/elastic-package version

      - name: Start the stack
        run: ~/go/bin/elastic-package stack up -d

      - name: Stop the stack
        run: ~/go/bin/elastic-package stack down
