name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  sanity:
    name: Sanity (${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        package-storage-ref: ["production"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout assets
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.package-storage-ref }}
          path: assets/${{ matrix.package-storage-ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make tests

      - name: Sanity checks
        run: make sanity
