name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  sanity:
    name: Sanity (${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make tests

      - name: Sanity checks
        run: make sanity

  plan:
    name: Plan update
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package-storage-ref: ["production", "staging", "snapshot"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout assets
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.package-storage-ref }}
          path: assets/${{ matrix.package-storage-ref }}

      - name: Checkout packages
        uses: actions/checkout@v2
        with:
          repository: elastic/package-storage
          ref: ${{ matrix.package-storage-ref }}
          path: packages/${{ matrix.package-storage-ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Make an update plan
        id: update-plan
        run: |
          echo "::set-output name=need-update::$(
            if [ -n "$(python3 -m bot plan | tee /dev/stderr)" ]; then
              echo yes
            else
              echo no
            fi
          )"

      - name: Install elastic-package
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          go install github.com/elastic/elastic-package@latest
          ~/go/bin/elastic-package version

      - name: Start the stack
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: ~/go/bin/elastic-package stack up -d

      - name: Update assets
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          git config --global user.name "The Elastic Assets Bot"
          git config --global user.email "noreply@elastic.co"
          export PATH=$PATH:~/go/bin
          eval "$(elastic-package stack shellinit)"
          python3 -m bot update

      - name: Push assets
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          git -C assets/${{ matrix.package-storage-ref }} push

      - name: Stop the stack
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: ~/go/bin/elastic-package stack down
