name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  package-sanity:
    name: Python package sanity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: make prereq

      - name: Build package
        run: make pkg-build

      - name: Check sanity
        run: make pkg-sanity
