name: Assets update

on:
  schedule:
    - cron: "6 */6 * * *"

  workflow_dispatch:

jobs:
  plan:
    name: Plan update
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package-storage-ref: ["production", "staging", "snapshot"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout assets
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.package-storage-ref }}
          path: assets/${{ matrix.package-storage-ref }}

      - name: Checkout packages
        uses: actions/checkout@v2
        with:
          repository: elastic/package-storage
          ref: ${{ matrix.package-storage-ref }}
          path: packages/${{ matrix.package-storage-ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Make an update plan
        id: update-plan
        run: |
          echo "::set-output name=need-update::$(
            if [ -n "$(python3 -m bot plan | tee /dev/stderr)" ]; then
              echo yes
            else
              echo no
            fi
          )"

      - name: Install elastic-package
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          go install github.com/elastic/elastic-package@latest
          ~/go/bin/elastic-package version

      - name: Start the stack
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          STACK_VERSION=`curl -s -H 'Accept: application/vnd.github+json' https://api.github.com/repos/elastic/elasticsearch/releases | \
            jq -r '.[] .tag_name' | \
            sort -V | \
            tail -n1 | \
            sed 's/v//'`
          ~/go/bin/elastic-package stack up -d -v $STACK_VERSION

      - name: Update assets
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          git config --global user.name "The Elastic Assets Bot"
          git config --global user.email "noreply@elastic.co"
          export PATH=$PATH:~/go/bin
          eval "$(elastic-package stack shellinit)"
          python3 -m bot update

      - name: Push assets
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: |
          git -C assets/${{ matrix.package-storage-ref }} push

      - name: Stop the stack
        if: ${{ steps.update-plan.outputs.need-update == 'yes' }}
        run: ~/go/bin/elastic-package stack down
